### ISSUE TITLE
cb_flush called before initialization

### ISSUE THREAD

**Issue by jbravar** [brianc/node-pg-copy-streams#57] opened 2016-10-31 21:59 UTC
There appears to be a condition that can arise where the `handleCommandComplete` callback is called before the first time `_flush` is called. This causes the below exception to occur:

```
TypeError: this.cb_flush is not a function
	at CopyStreamQuery.handleCommandComplete (./node_modules/pg-copy-streams/index.js:67:8)
	at Connection.<anonymous> (./node_modules/pg/lib/client.js:132:24)
	at emitOne (events.js:96:13)
	at Connection.emit (events.js:188:7)
	at Socket.<anonymous> (./node_modules/pg/lib/connection.js:121:12)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:188:7)
	at readableAddChunk (_stream_readable.js:176:18)
	at Socket.Readable.push (_stream_readable.js:134:10)
	at TCP.onread (net.js:548:20)
```

I added a little logging to confirm:

![screen shot 2016-10-31 at 5 45 58 pm](https://cloud.githubusercontent.com/assets/160371/19873001/efb7a016-9f92-11e6-9be4-881d85b3814e.png)

I'm having a hard time figuring out exactly what's causing it, though it seems like larger input files tend to trigger it. Here's the SQL statement I'm using:

```
BEGIN;
TRUNCATE locations RESTART IDENTITY;
COPY my_table(my_fields) FROM STDIN CSV;
COMMIT;
```

Is it possible the transaction block is causing this? I'm on the latest versions of both `pg` and this module as of writing.

_Edit: node version 6.9.1_

**Comment by jbravar** [comment] 2016-10-31 22:15
If anyone's being blocked by the same issue, nooping the function seems to work:

```
const copier = copyFrom(stmt);
copier.cb_flush = () => {};
const stream = client.query(copier);
```

**Comment by jeromew** [comment] 2016-11-01 08:45
Hello,
thanks for the report. I will have to check your use case but it probably is due to the transaction block where the library was designed to handle a single sql COPY command.

I understand that the log that you provide comes from 1 execution of the code. If this is true, that would mean that 1/ begin; 2/ truncate; generate the first 2 commandComplete events. They error because the code does not expect them. The 3rd woks as expected. and the 4th is for commit;.

Can you confirm that the 4 commandComplete in your log come from only 1 execution of the code ?

**Comment by jbravar** [comment] 2016-11-01 12:34
Ah yes, this makes sense. And yes that log output is from one run, sorry I should've been a little clearer about that. I wonder if below a certain number of rows Postgres does something differently, the fact that smaller datasets weren't triggering this behaviour threw me off.

**Comment by jeromew** [comment] 2019-03-19 08:44
At this stage I don't see how to handle this use case so I'll close the issue.

**Closed by jeromew** 2019-03-19 08:44 UTC
