### ISSUE TITLE
Error Callback Not Initiating on PG Constraint Error

### ISSUE THREAD

**Issue by BrandonMcNary** [brianc/node-pg-copy-streams#21] opened 2015-01-20 21:55 UTC
Hi Brian,

Thank you so much for this tool. It easily streams 40,000 rows + into our Postgres database. I have one issue though, I'm unable to get it to throw errors when there is a problem. Certain tables within our database have unique constraints. When a user attempts to upload a duplicated file, the database throws an error, but I can't get this to bubble back to the user. I've tinkered with the error callback provided, but for whatever reason it doesn't trigger when a database error is thrown. 

Do you have any recommendations? Please let me know if I'm doing something wrong here. 

Thanks again!
Brandon

I'm using this code:

pg.connect(connectionString, function(err, client, done) {
        if(err) {
            return console.error('could not connect to postgres', err);
        }
        var stream = client.query(copyFrom(query));
        var s = new Readable;
        s.push(csv);
        s.push(null);
        s.pipe(stream).on('finish', function () {
            res.send(200);
            done();
        }).on('error', function () {
            res.send(500);
            done();
        });
    });
};

**Comment by brianc** [comment] 2015-01-21 14:39
Oh sorry that's happening! Hmm would it be possible to sumit a fully
executable sample that reproduces the problem? I have tests To check for
errors being emitted properly but streams emit errors in confusing ways. A
working snippet should help me pinpoint it.

**Comment by BrandonMcNary** [comment] 2015-01-27 06:04
Hi Brian,

Thanks for the quick reply. I was trying to figure out how to achieve this, as a front to back sample would be quite a bit of work. Is there something specifically you'd like to see? The code I pasted was a portion of the uploadData function. I pasted the rest of the server code surrounding the uploadData function below. I've also included the angular service which handles the HTTP request to the server after a user has submitted the file. Sorry it's not the sample you wanted. If you have any suggestions to get you what you're looking for, please let me know.

Kind Regards,
Brandon

'use strict'
var knex = require(__dirname+'/../../knexconfig.js').knex;
var connectionString = require(__dirname+'/../../knexconfig.js').connectionString;
var pg = require('pg');
var copyFrom = require('pg-copy-streams').from;
var fs = require ('fs');
var Readable = require('stream').Readable;

var uploadData = function(req, res){
    var csv = ConvertToCSV(req.body),
        table,
        trendType = (req.param('trendType') === 'Energy') ? 'electric' : 'power';

    if (req.param('uploadType') === 'dataInterval'){
        table = trendType + 'datainterval';
    }
    if (req.param('uploadType') === 'waterInterval'){
        table = 'waterdata';
    }
    var query = 'COPY ' + table + ' FROM STDIN';
    pg.connect(connectionString, function(err, client, done) {
        if(err) {
            return console.error('could not connect to postgres', err);
        }
        var stream = client.query(copyFrom(query));
        var s = new Readable;
        s.push(csv);
        s.push(null);

        s.pipe(stream).on('finish', function () {
            res.send(200);
            done();
        }).on('error', function () {
            res.send(500);
            done();
        });
    });
};

var ConvertToCSV = function(objArray) {
    var array = typeof objArray != 'object' ? JSON.parse(objArray) : objArray;
    var str = '';
    for (var i = 0; i < array.length; i++) {
        var line = '';
        for (var index in array[i]) {
            if (line != '') line += '\t'
            line += array[i][index];
        }
        str += line + '\r\n';
    }
    return str;
};

--- End Server
-- Start Angular HTTP Service
//HTTP query launched when a user submits a CSV file (fileObject is the CSV)

 return helpers = {
    saveEnergyUse: function(fileObject, trendType, uploadType, farmId, companyId){
      var deferred = $q.defer();
      $http({
        method: 'POST',
        url: '/api/uploadData/' + uploadType + '/' + trendType,
        data: fileObject,
      }).success(function(record){
        deferred.resolve(record);
      }).error(function(info, status){
        deferred.reject('Error', info, 'Status', status);
      console.error(info);
      });
      return deferred.promise;
    }
}

--- END Angular Service

**Comment by BrandonMcNary** [comment] 2015-02-10 21:36
Hi Brian,

Just following up on this. Please let me know if you require anything further!

Thanks,
Brandon

**Comment by dimfeld** [comment] 2015-03-21 21:42
I'm seeing the same problem. Here's a self-contained test that reproduces the issue: https://gist.github.com/dimfeld/6bc7d921040f9b6eeaed

This is using Postgres 9.4.0, and I've seen the problem on both Mac and Ubuntu 14.04.

**Comment by dimfeld** [comment] 2015-03-22 09:19
Oops, this was my mistake. In both my test case here and my original code, I was handling the `finish` event, when I should have been handling `end`. If I handle `end` instead then I see the error as expected. 

Brandon, I think your code above has the same problem. If you change it to `.on('end',` does it start working for you?

**Comment by jeromew** [comment] 2016-08-23 12:32
I just fixed the documentation regarding finish vs end.
The current implementation inherits from a Transform stream. 'finish' is triggered too early by the Transform stream because we need to way from an async ACK from the database even if all the data has already been written to the socket.
As of now, you need to wait for 'end' which is triggered after we receice this ACK.

In both your cases you are sending a csv blob to the db, which triggers the 'finish' once it is all gone on the db socket, but probably before the db has time to realise there is an error.

Please try with version 1.2.0 + listening for 'end' instead of 'finish'.

You can read more on #15 regarding the finish vs end debate.

I am closing this issue. Please reopen if this does not fix your problem.

**Closed by jeromew** 2016-08-23 12:32 UTC
