### ISSUE TITLE
Hangs during repeated use

### ISSUE THREAD

**Issue by banderson5144** [brianc/node-pg-copy-streams#24] opened 2015-04-27 21:48 UTC
I am recursively calling a method that issues a COPY TO query. The first time always works, but the second time just hangs there, nothing happening. I can provide a code sample if needed.

**Comment by drob** [comment] 2015-04-27 21:54
How are you acquiring the node-pg client, and where are you releasing it?

That code sample would definitely be helpful.

**Comment by banderson5144** [comment] 2015-04-27 22:06
An extremely chopped down version of my code (due to sensitive information) but you'll get the gist. First go round works, second time it just hangs.

```
var connObj = {
    user: "xx",
    password: "xx",
    database: "xx",
    port: 5522,
    host: "xx-xx-xx-xx",
    ssl: true
};

var rows = [];
var myClient = new pg.Client(connObj);
myClient.connect();

var query = myClient.query('SELECT * FROM table');
    query.on('row', function(row) {
      //fired once for each row returned
      rows.push(row);
    });
    query.on('end', function(result) {
      callFunc();
    });

function callFunc()
{
  var stream = client.query(copyTo('COPY (SELECT * FROM table WHERE my_col =\''+ rows[0] + '\' TO STDOUT'));
  var writeStream = fs.createWriteStream('test.csv');
      stream.pipe(writeStream);
      stream .on('end', function(result) {
        callFunc();
      });
}
```

**Comment by banderson5144** [comment] 2015-04-27 22:19
Is that good enough?

**Comment by banderson5144** [comment] 2015-04-28 12:18
Any ideas? Sorry I'm being pushy, time sensitive

**Comment by shaunc** [comment] 2015-05-31 02:35
I'm getting something similar. I find if I put in a delay it works... but an annoyingly long delay.

Usually I promisify using bluebird and use "queryAsync". When we use "client.query" like this is the client really ready for reuse before the "end" event on the stream? If not can we pass a callback? I tried using queryAsync, and also passing a callback but no luck.

**Comment by shaunc** [comment] 2015-05-31 04:02
@drob -- for me, I have roughly:

    pg.connect( function(err, client, done) {
      stream = client(copyFrom( ... ));
      stream.on('end', function() { 
        done();
       f();  });
     ... (consume string....)...

    });

And then ...

    function f () {
      pg.connect( function(err, client, done) {
        client.query( ... )
      });
   }

In the f(), the client is the same processID as before. Also

    client.readyForQuery

is false, and the active query is I think the streaming query. Yet this is only triggered on "end" event of stream. Is there a different event we should be listening to, to ensure that stream query is really done?


This 2nd query hangs. However, if I put in "debugger" right before I execute, and pause a moment there, then the 2nd query executes after all.

**Comment by shaunc** [comment] 2015-05-31 05:16
A working workaround (for me): replace the stream "end" listener with

    stream.on('end', function() {
      client.connection.once("readyForQuery", function() {
        done();
      });
    });

I would guess that this could be moved to `CopyStreamQuery.prototype.handleCommandComplete` --
(ie put in connection listener there) but I don't know enough about the code to say whether that would be a good idea or a terrible hack (probably the latter, as its hard to write good code without understanding what is going on :)). I note some calls to con.sync() ... perhaps that is needed/ would be a better solution? On the other hand, why does the next query not just queue if we aren't done yet? Perhaps the stream query "looks done" once it has streamed everything even if the underlying connection is still processing.

**Comment by shaunc** [comment] 2015-06-01 01:14
(fix in [https://github.com/brianc/node-pg-copy-streams/issues/28](pull request))

**Comment by cbaron** [comment] 2016-05-02 16:25
Was this fixed?  I'm having similar issues.

**Comment by jeromew** [comment] 2016-08-23 12:39
I never run into this issue. It woud be interesting to have a test case using 1.2.0. you can find test examples in the test directory. @shaunc I closed #28 as non-mergeable. I would be interested if you could tell me if 1.2.0 fixes the issue because I did not fully understand the need for the pause/resume handling in the #28 PR.

**Comment by furstenheim** [comment] 2018-11-12 08:59
I've seen the same issue. In my case it would happen if the amount of data was big enough. So a csv with 800 lines would work perfectly, a csv with 4k lines would fail. By failing I mean that subsequent queries wouldn't get executed. pg_stat_activity didn't show any query.

**Comment by jeromew** [comment] 2019-03-15 13:39
Thanks for the report. Currently there are no tests regarding the client reuse after COPY. From what I remember the scenario was not taken into account during dev and it is expected that the client will be closed/released after use. There may be corner cases with pools so this is probably worth investigating or at least understand and document when it is ok to start sending new queries to the client. The pause/resume fix that was considered in #28 is maybe still worth looking at but there have been so many node & stream versions since then that it might also be non related.

I'll try and create failing tests regarding this in the next few days.

**Comment by jeromew** [comment] 2019-03-15 15:17
@furstenheim I just added a test in test/copy-to.js regarding client reuse for copy-to. At this stage I cannot get it to fail. was you failure mode with copy-to or copy-from ?

**Comment by jeromew** [comment] 2019-03-18 17:50
I added a test in test/copy-from regarding client reuse for copy-from. At this stage I cannot get it to fail even with large inputs.

I'll close this issue. feel free to re-open if needed & if you succeed modify the tests and make them fail. thanks.

**Closed by jeromew** 2019-03-18 17:50 UTC

**Comment by furstenheim** [comment] 2019-03-26 18:40
@jeromew yes, it was in copy from. It didn't always happen, but with a loop of copy froms and only one client it would get stuck after around 15 iterations (something like a thousand lines). To fix it I had to manually execute client.connection.resume()

**Comment by jeromew** [comment] 2019-03-27 10:29
@furstenheim thanks for the feedback. I could not reproduce the issue but it might be a rare timing issue between the end of the COPY command and the `readyForQuery` event. I'll have to dig into that.
